--js-runtimes
node:/usr/bin/node

--remote-components
ejs:github

--paths
/home/appuser/downloads

--output
%(title)s [%(id)s].%(ext)s

--format
bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]

--merge-output-format
mp4

--no-mtime
--continue
--no-part
